### ISSUE TITLE
No voice chat?

### ISSUE THREAD

**Issue by BlackReaper33** [sentrionic/ValkyrieApp#10]
I read your update on [Parent repository](https://github.com/sentrionic/Valkyrie) that you added voice chat which i was super excited about but it seems you haven't added one for mobile. So i was wondering if you'd be adding one?
And since i have already opened an issue i just wanted to give a suggestion if you could add **@** mention user function with in a guild?

**Comment by sentrionic** [comment]
I currently don't have the interest / time to add WebRTC to the app no.
Same goes for your other suggestion.

**Comment by BlackReaper33** [comment]
Ok thanks for the reply!

**Comment by BlackReaper33** [comment]
.
