### ISSUE TITLE
Single backend connection

### ISSUE THREAD

**Issue by itsbek** [sentrionic/ValkyrieApp#8]
hello @sentrionic 
congrats on your successful completion of the mobile version!

I have heard about single backend solutions for web and mobile apps, but this is my 1st time trying out myself. Could you please walk through the stages on how you connected to existing backend on mobile?

changing the `BaseUrl` value in `InjectableModule` is clear but the rest is a bit blurry in my mind...

thanks in advance!

**Comment by sentrionic** [comment]
I'm not sure if I understand the question correctly.
The backend uses the REST protocol which sends JSON responses back.
So similarly to the web client (Axios), the Flutter app uses an http client (Dio) to send and fetch requests.
To authenticate those requests it sends the Express Session cookie, which unlike in browsers needs to be explicitly set in the interceptor.

**Comment by itsbek** [comment]
sorry being unclear on my question, haha...

in short what I meant is, just changing the `BaseUrl` value will do the job? no need to add/change anything on the backend -heroku side?

**Comment by sentrionic** [comment]
Yes you only need to change the url.

**Comment by itsbek** [comment]
I did so, it logs me in but wont display any info about user(me) and messages, servers etc. - won't sync up...

**Comment by sentrionic** [comment]
Well I don't remember changing anything server side for it to work, so I guess you will need to print your errors to see what's wrong. Does it work with my url?

**Comment by itsbek** [comment]
it works fine with your link, once I change it to mine it won't respond - however it logs in(but without any data about logged in user)

**Comment by sentrionic** [comment]
As I mentioned in the other thread debugging remotely is difficult.
As far as I know I didn't change anything on the server or on heroku.

**Comment by itsbek** [comment]
this is what's coming while compiling, tried out some solutions from stackoverflow, github - but it still persists

![Screenshot_14](https://user-images.githubusercontent.com/65237794/119024567-a2b9ae00-b9bc-11eb-9de9-2817f1db2995.png)

**Comment by sentrionic** [comment]
The keyboard shouldnt have anything to do with the network and it being deprecated means that for now it's still working.
